name: SVG → WebP (auto + manual)

# Triggers:
#  - on push to svg/** (any branch)
#  - manual run from Actions UI
on:
  push:
    paths:
      - "svg/**"
    # avoid recursive triggers when webp/ is pushed
    paths-ignore:
      - "webp/**"
  workflow_dispatch:

# Give action permission to write files (needed for git push)
permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # allow pushes with GITHUB_TOKEN
          fetch-depth: 0

      - name: Show environment & basic debug info
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "Running on runner: $(uname -a)"
          echo "List repo root:"
          ls -la

      - name: List svg folder (if present)
        run: |
          if [ -d svg ]; then
            echo "SVG DIR FOUND:"
            ls -la svg || true
          else
            echo "❌ svg/ folder NOT found"
            exit 0
          fi

      - name: Install webp tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y webp imagemagick || true
          cwebp -version || true

      - name: Convert SVG → WebP (safe)
        run: |
          mkdir -p webp
          converted=0
          for file in svg/*.svg; do
            [ -f "$file" ] || continue
            base=$(basename "$file" .svg)
            out="webp/${base}.webp"
            echo "Converting: $file -> $out"
            # Render PNG then convert to webp for consistent results
            # Use rsvg-convert if available; fallback to convert
            if command -v rsvg-convert >/dev/null 2>&1; then
              rsvg-convert -w 1000 -h 1000 "$file" -o "/tmp/${base}.png" || convert "$file" "/tmp/${base}.png"
            else
              convert "$file" "/tmp/${base}.png" || true
            fi
            # create WebP with quality 85 and effort 6
            if [ -f "/tmp/${base}.png" ]; then
              cwebp -q 85 -m 6 "/tmp/${base}.png" -o "$out" && converted=$((converted+1))
              rm -f "/tmp/${base}.png"
            else
              # try direct cwebp from svg (ImageMagick may support it)
              cwebp -q 85 "$file" -o "$out" && converted=$((converted+1)) || echo "⚠️ Could not create /tmp/${base}.png nor convert $file directly"
            fi
          done
          echo "Total converted: $converted"
          if [ "$converted" -eq 0 ]; then
            echo "No conversions performed — exiting without commit."
            exit 0
          fi

      - name: Commit & push WebP files (only if changes)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add webp || true
          # show diff
          git status --porcelain
          if git diff --cached --quiet; then
            echo "No new/changed files to commit."
            exit 0
          fi
          git commit -m "Auto: SVG → WebP conversion [ci skip]" || true
          # Push to the same branch the workflow was triggered on
          # Determine branch (GITHUB_REF could be refs/heads/<branch>)
          branch=${GITHUB_REF#refs/heads/}
          echo "Pushing to branch: $branch"
          git push origin "HEAD:$branch"
